### PR TITLE
Fixes 5.8

### PR DESCRIPTION
**Pull request by papadil**
In order to compile on MacOS 10.15 (Catalina) I had to comment line 58 of machoexport.cpp which attempts to include a <mach-o/ppc/reloc.h> which does not exist. I'm new to Git so pardon me if I'm not doing this right.

### CODE REVIEW

**Comment by pclayton** [comment]
This was fixed by #119.  Does the latest master build for you?  I don't think that fix has been ported to the fixes-5.8 branch though.

**Comment by papadil** [comment]
> This was fixed by #119. Does the latest master build for you? I don't think that fix has been ported to the fixes-5.8 branch though.
I tried the master branch before the fixes-5.8 and had the same error. So I was hoping the fixes-5.8 branch would compile.  Thanks.

**Comment by pclayton** [comment]
The problematic line isn't there in the latest master - [see here](https://github.com/polyml/polyml/blob/master/libpolyml/machoexport.cpp#L58) - so I don't think you can be building the latest master.

Are you using a Git repository?  What do
`git branch`
`git log`
show?

Also, in case it's useful, Poly/ML 5.7.1 is available via [MacPorts](https://ports.macports.org/port/polyml/summary) and that does build on Mac OS 10.15.

**Comment by papadil** [comment]
I went back and realized my error - previously I built the release-5.8 not the master.  My bad.  Sorry for the confusion.

**Pull request closed without merging**
