### PR TITLE
sem_wait require -lpthread on linux

### PR DESCRIPTION
**Pull request by atupone**

### CODE REVIEW

**Comment by dcjm** [comment]
Thank you for contribution.  However, this does not look right.  `AC_SEARCH_LIBS` is used to add the library to the list of libraries used by the linker if it is necessary.  The purpose of the line that reads
`AC_SEARCH_LIBS([sem_wait], [rt])`
is to add `rt` to the linker line on Solaris because `sem_wait` is not in the pthread library on that platform.

**Comment by atupone** [comment]
I kno wis not a slaris problem.
But sem_wait needs pthread and pthread is not in the in the linker command line. This actually fix a build failure when configure is run without x and without threads. See
https://bugs.gentoo.org/606096

**Comment by dcjm** [comment]
It looks like there is a problem when compiling when the `--without-threads` option is given.  That needs to be investigated.  One possibility is to remove that option.  Why do you need this option?

**Comment by atupone** [comment]
It is one of the possibility given by polyml at configure, and we, at gentoo, don't want to limit the choices to the user. If you are going to remove it, we will do the same

**Pull request closed without merging**
