### PR TITLE
Add "-ld_classic" into LDFLAGS if available

### PR DESCRIPTION
**Pull request by binghe**
Hi,

The purpose of this PR is to fix Poly/ML building issues in recent versions of macOS (see #192 and #194). The idea is that, whenever the linker flag `-ld_classic` is supported (no matter if this is on macOS or not), it's added into `LDFLAGS`, not only for building Poly/ML itself, but also part of the `polyc` script.  I have spent a little time learning `autoconf` and your existing code in `configure.in`.

The detection of linker flags is done by a M4 macro called `AX_CHECK_LINK_FLAG` (copied from GNU autotools-archive to `m4/ax_check_link_flag.m4`):
```
AX_CHECK_LINK_FLAG([-ld_classic],
    [LDFLAGS="$LDFLAGS -ld_classic"
     use_classic_linker=yes],
    [use_classic_linker=no])
```
Beside pushing `-ld_classic` into environment variable `LDFLAGS` for building Poly/ML itslef, the above defined variable `use_classic_linker` is further used to define a "AM_CONDITIONAL" called `CLASSIC_LINKER`:

```
AM_CONDITIONAL([CLASSIC_LINKER], [test "$use_classic_linker" = yes])
```

Finally, in `polyc.in`, an extra line of `EXTRALDFLAGS="-ld_classic"` is added when calling the linker.
```
# Extra options for macOS
@CLASSIC_LINKER_TRUE@EXTRALDFLAGS="-ld_classic"
```

Note also that, sometimes in the generated `polyc` script, the value of `LINK` is something like `/usr/bin/clang++ -std=gnu++11` (the compiler execution and another flags, separated by a whitespace).  I think this is a behavior of higher versions of autoconf.  In this case you cannot write `"${LINK}" ${LDFLAGS} ...` to call the linker, because this whole string `"${LINK}"` will be treated as a single filename, which does not exist then...  I don't know what will happen if the compiler itself is installed in a path which itself contains directory names with spaces, but this case should be rare. A obvious workaround of this issue is to simply delete the double-quotes around `${LINK}`. This is exactly what I did.

P.S. I actually don't know how to run the `AX_CHECK_LINK_FLAG` check in only macOS, but the current way should be safe for other OSs. Anyway, feel free to further modify my solution.

--Chun

### CODE REVIEW

**Comment by binghe** [comment]
I see your current `configure` script is generated by autoconf 2.71. This version is not available in my machine. My changes are confirmed with autoconf 2.69, while with autoconf 2.72 the generated `configure` scripts is broken with grammar errors (irrelevant with my changes).  Therefore I'd like to see how the updated `configure` script (still with autoconf 2.71) will work in my machine.

**Comment by binghe** [comment]
It's possible that putting `-ld_classic` into `LDFLAGS` will cause "library not found for -ld_classic" errors for linkers who doesn't understand `-ld_classic` (and treats it as linking a non-exist library called "d_classic"). But such errors should be captured during the `AX_CHECK_LINK_FLAG` tests, thus still safe.

**Comment by pclayton** [comment]
> Note also that, sometimes in the generated `polyc` script, the value of `LINK` is something like `/usr/bin/clang++ -std=gnu++11` (the compiler execution and another flags, separated by a whitespace). I think this is a behavior of higher versions of autoconf. In this case you cannot write `"${LINK}" ${LDFLAGS} ...` to call the linker, because this whole string `"${LINK}"` will be treated as a single filename, which does not exist then... I don't know what will happen if the compiler itself is installed in a path which itself contains directory names with spaces, but this case should be rare. A obvious workaround of this issue is to simply delete the double-quotes around `${LINK}`. This is exactly what I did.

The double quotes in `"${LINK}"` would ensure that a path containing spaces is correctly handled but, as you observe, this doesn't work if `${LINK}` also contains arguments (which are separated by spaces).  The [Autoconf documentation](https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/File-System-Conventions.html) indicates that file and directory names containing spaces are not supported so I think it makes sense to remove these double quotes as you have done.

**Comment by binghe** [comment]
The way I set `EXTRALDFLAGS="-ld_classic"` in `polyc.in` may overwrite previous values for native Windows (if somehow the linkers there support `-ld_classic`). I hope you can find a better way to achieve the same goal.

P.S. Currently the macports package "polyml" is broken on macOS Sonoma because of this linker issue.

**Comment by binghe** [comment]
glad to see that the root cause has been fixed.

**Pull request closed without merging**
