### PR TITLE
Enable Visual Styles for Windows GUI

### PR DESCRIPTION
**Pull request by jrtc27**
This makes Windows style the dialog boxes to look modern, rather than using the old plain grey look.

### CODE REVIEW

**Comment by dcjm** [comment]
I've tried this out and I can't see any difference in either Windows 7 or Windows 10. What effect should it have? Is there something else that's needed?
David

**Comment by jrtc27** [comment]
The main window itself is unaffected; it's just the styling of the dialog boxes. This is what it looks like for me on Windows 10:

### Before
visual-styles-without-about
visual-styles-without-quit

### After
visual-styles-with-about
visual-styles-with-quit

**Comment by dcjm** [comment]
Thanks.  It only seems to affect the buttons.  I wasn't looking closely enough.

**Comment by jrtc27** [comment]
Yeah it's not exactly drastic. Thanks.

**Pull request merged**
